### ISSUE TITLE
Scheduler dies if deployctl is not available.

### ISSUE THREAD

**Issue by sarnowski** [zalando-zmon/zmon-scheduler#7]
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'createScheduler' defined in class path resource [de/zalando/zmon/scheduler/ng/SchedulerFactory.class]: Unsatisfied dependency expressed through constructor argument with index 2 of type [de.zalando.zmon.scheduler.ng.entities.EntityRepository]: : Error creating bean with name 'entityRepository' defined in URL [jar:file:/..../application.jar!/de/zalando/zmon/scheduler/ng/entities/EntityRepository.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.zalando.zmon.scheduler.ng.entities.EntityRepository]: Constructor threw exception; nested exception is org.springframework.web.client.HttpServerErrorException: 502 Bad Gateway; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityRepository' defined in URL [jar:file:/..../application.jar!/de/zalando/zmon/scheduler/ng/entities/EntityRepository.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.zalando.zmon.scheduler.ng.entities.EntityRepository]: Constructor threw exception; nested exception is org.springframework.web.client.HttpServerErrorException: 502 Bad Gateway
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:749)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:464)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1111)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1006)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
    ... 24 more
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityRepository' defined in URL [jar:file:/..../application.jar!/de/zalando/zmon/scheduler/ng/entities/EntityRepository.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.zalando.zmon.scheduler.ng.entities.EntityRepository]: Constructor threw exception; nested exception is org.springframework.web.client.HttpServerErrorException: 502 Bad Gateway
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:275)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1131)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1034)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1120)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1044)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
    at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:813)
    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:741)
    ... 37 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.zalando.zmon.scheduler.ng.entities.EntityRepository]: Constructor threw exception; nested exception is org.springframework.web.client.HttpServerErrorException: 502 Bad Gateway
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
    ... 50 more
Caused by: org.springframework.web.client.HttpServerErrorException: 502 Bad Gateway
    at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:94)
    at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:615)
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:573)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:529)
    at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:329)
    at de.zalando.zmon.scheduler.ng.entities.DeployCtlInstanceAdapter.getCollection(DeployCtlInstanceAdapter.java:57)
    at de.zalando.zmon.scheduler.ng.entities.EntityRepository.fill(EntityRepository.java:110)
    at de.zalando.zmon.scheduler.ng.entities.EntityRepository.<init>(EntityRepository.java:221)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
    ... 52 more
ERROR copying MANIFEST.MF
```

**Comment by hjacobs** [comment]
:+1: we need to make it more resilient

**Comment by Jan-M** [comment]
Catching exception in getting data from deployctl for instances in project should avoid this upstart problem.

Will however return empty list, ideally the last result should remain(no longer important imho)
